name: CI Pipeline for Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get short commit SHA
      id: vars
      run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-image-name:${{ steps.vars.outputs.short_sha }} .

    - name: Run tests
      run: |
        # Ajoute ici les commandes pour exécuter tes tests
        echo "Running tests..."
        # Exemple de test (à remplacer par tes propres tests)
        docker run --rm your-dockerhub-username/your-image-name:${{ steps.vars.outputs.short_sha }} /bin/sh -c "echo Tests passed"
