name: CI Pipeline for Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get short commit SHA
      id: vars
      run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-image-name:${{ steps.vars.outputs.short_sha }} .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push your-dockerhub-username/your-image-name:${{ steps.vars.outputs.short_sha }}
